ad-course-ecom-daham/Models/Product/Category.cs
using System.ComponentModel.DataAnnotations;

namespace ad_course_ecom_daham.Models.Product
{
    public class Category
    {
        [Key]
        public Guid cateId { get; set; }

        public string cateName { get; set; }
    }
}

ad-course-ecom-daham/Models/Product/ComVariation.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ad_course_ecom_daham.Models.Product
{
    public class ComVariation
    {
        [Key]
        public Guid comvId { get; set; }
        public string comvName { get; set; }
        [ForeignKey("computer")]
        public Guid comId { get; set; }
        public Computer computer { get; set; }
        [NotMapped]
        public List<ComVariationOption> variationOptions { get; set; }
    }
}

ad-course-ecom-daham/Controllers/AdminDashboardController.cs
using ad_course_ecom_daham.Business.Interfaces;
using ad_course_ecom_daham.Models;
using ad_course_ecom_daham.Models.CustomerModels;
using ad_course_ecom_daham.Models.Product;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using System.Net;
using ad_course_ecom_daham.Models.Chart;
using Newtonsoft.Json;

namespace ad_course_ecom_daham.Controllers
{
    public class AdminDashboardController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ISeriesService _seriesService;
        private readonly IComputerService _computerService;
        private readonly IVariationService _variationService;
        private readonly IVariationOptionService _variationOptionService;
        private readonly IOrderService _orderService;
        private readonly IOrderItemService _orderItemService;
        private readonly ICustomerService _customerService;
        List<Series> _seriesList;
        List<Category> _categories;
        List<Computer> _computerList;
        List<Order> _ordersList;
        List<Customer> _customersList;
        List<ComVariation> _variationList = new List<ComVariation>();
        public AdminDashboardController(IOrderItemService orderItemService, ICustomerService customerService, IOrderService orderService, IVariationOptionService variationOptionService, IVariationService variationService, ICategoryService categoryService, ISeriesService seriesService, IComputerService computerService) {
            _categoryService = categoryService;
            _seriesService = seriesService;
            _computerService = computerService;
            _variationService = variationService;
            _variationOptionService = variationOptionService;
            _orderService = orderService;
            _orderItemService = orderItemService;
            _customerService = customerService;
        }

        /* 
            Load Orders report details.
            Load Customer report data and pass it to View using ViewBag.
            Load Current stock report data and pass it to View using ViewBag.
        */
        public IActionResult Index()
        {
            _ordersList = _orderService.GetOrders();
            _customersList = _customerService.GetCustomers();
            for (int i = 0; i < _ordersList.Count; i++)
            {
                Customer customer = _customerService.GetCustomerById(_ordersList[i].cId);
                _ordersList[i].customer = customer;
                _ordersList[i].totalPrice = decimal.Round(_ordersList[i].totalPrice, 2, MidpointRounding.AwayFromZero);
                List<OrderItem> orderItemList = _orderItemService.GetOrderItemById(_ordersList[i].oId);
                _ordersList[i].orderItems = orderItemList;
                for (int j = 0; j < _ordersList[i].orderItems.Count; j++)
                {
                    Computer orderComputer = _computerService.GetComputerById(_ordersList[i].orderItems[j].comId);
                    _ordersList[i].orderItems[j].computer = orderComputer;
                }
            }
            ViewBag.orders = _ordersList;
            ViewBag.customers = _customersList;
            ViewBag.isManageCategories = false;

            List<DataPoint> dataPoints = new List<DataPoint>();
            _computerList = _computerService.GetComputers();
            for(int i=0; i< _computerList.Count; i++)
            {
                dataPoints.Add(new DataPoint(_computerList[i].cName, _computerList[i].qty));
            }

            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
            return View("../Admin/AdminDashboard");
        }

        public IActionResult OpenManageOrders()
        {
            List<string> orderStatus = new List<string>();
            orderStatus.Add("Pending");
            orderStatus.Add("In process");
            orderStatus.Add("Dispatched");
            orderStatus.Add("Delivered");

            _ordersList = _orderService.GetOrders();
            for (int i = 0; i < _ordersList.Count; i++)
            {
                Customer customer = _customerService.GetCustomerById(_ordersList[i].cId);
                _ordersList[i].customer = customer;
                List<OrderItem> orderItemList = _orderItemService.GetOrderItemById(_ordersList[i].oId);
                _ordersList[i].orderItems = orderItemList;
                for (int j = 0; j < _ordersList[i].orderItems.Count; j++)
                {
                    Computer orderComputer = _computerService.GetComputerById(_ordersList[i].orderItems[j].comId);
                    _ordersList[i].orderItems[j].computer = orderComputer;
                }
            }
            ViewBag.orders = _ordersList;
            ViewBag.orderStatus = orderStatus;
            return View("../Order/AdminOrderView");
        }

        /*
            Load all computers as a List and pass it to view using a Viewbag. 
        */
        public IActionResult ProductMainView()
        {
            try
            {
                _computerList = _computerService.GetComputers();
                _seriesList = _seriesService.GetSeries();
                _categories = _categoryService.GetCategories();
                for (int i = 0; i < _computerList.Count; i++)
                {
                    _computerList[i].seriesName = _seriesList.Where((s) => s.seriesId == _computerList[i].seriesId).FirstOrDefault().seriesName;
                    _computerList[i].cateName = _categories.Where((s) => s.cateId == _computerList[i].cateId).FirstOrDefault().cateName;
                    _computerList[i].normalPrice = decimal.Round(_computerList[i].normalPrice, 2, MidpointRounding.AwayFromZero);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            ViewBag.isManageCategories = false;
            ViewBag.computerList = _computerList;
            ViewBag.isManageSeries = false;
            ViewBag.viewProduct = true;
            return View("../Product/ProductView");
        }

        public IActionResult OpenManageCategories()
        {
            _categories = _categoryService.GetCategories();
            ViewBag.categories = _categories;
            ViewBag.isManageCategories = true;
            ViewBag.viewProduct = false;
            ViewBag.isManageSeries = false;
            return View("../Product/ProductView");
        }

        /* 
            Add a new category using the data passed from the post method. 
        */
        [HttpPost]
        public IActionResult AddCategory(string categoryName)
        {
            Category category = new Category();
            category.cateName = categoryName;
            _categoryService.AddCategory(category);
            _categories = _categoryService.GetCategories();
            ViewBag.categories = _categories;
            ViewBag.isManageCategories = true;
            ViewBag.viewProduct = false;
            ViewBag.isManageSeries = false;
            return View("../Product/ProductView");
        }

        public IActionResult OpenManageSeries()
        {
            try
            {
                List<Series> series = _seriesService.GetSeries();
                _categories = _categoryService.GetCategories();
                for (int i = 0; i < series.Count; i++)
                {
                    Category category = _categories.Where((c) => c.cateId == series[i].cateId).FirstOrDefault();
                    series[i].categoryName = category.cateName;
                }
                ViewBag.series = series;
                ViewBag.categories = _categories;
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
           
            ViewBag.isManageSeries = true;
            ViewBag.viewProduct = false;
            ViewBag.isManageCategories = false;
            return View("../Product/ProductView");
        }

        [HttpPost]
        public IActionResult AddSeries(string seriesName, string categoryName)
        {
            Series newSeries = new Series();
            try
            {
                _categories = _categoryService.GetCategories();
                newSeries.seriesName = seriesName;
                Category cc = _categories.Where((c) => c.cateName == categoryName).FirstOrDefault();
                newSeries.cateId = cc.cateId;
                _seriesService.AddSeries(newSeries);
                List<Series> series = _seriesService.GetSeries();
                for (int i = 0; i < series.Count; i++)
                {
                    Category ca = _categories.Where((c) => c.cateId == series[i].cateId).FirstOrDefault();
                    series[i].categoryName = ca.cateName;
                }

                ViewBag.series = series;
                ViewBag.categories = _categories;
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            ViewBag.isManageSeries = true;
            ViewBag.isManageCategories = false;
            ViewBag.viewProduct = false;
            return View("../Product/ProductView");
        }

        public IActionResult OpenAddComputer() {
            try
            {
                _seriesList = _seriesService.GetSeries();
                _categories = _categoryService.GetCategories();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            ViewBag.series = _seriesList;
            ViewBag.categories = _categories;
            ViewBag.isManageSeries = false;
            ViewBag.isManageCategories = false;
            ViewBag.isAddComputer = true;
            ViewBag.viewProduct = false;
            ViewBag.computerStatus = "";
            ViewBag.variationList = _variationList;
            ViewBag.isVariationMode = false;
            return View("../Product/ProductView");
        }

ad-course-ecom-daham/Controllers/AuthController.cs
using ad_course_ecom_daham.Models.Chart;
using ad_course_ecom_daham.Models.CustomerModels;
using ad_course_ecom_daham.Models.Product;
using ad_course_ecom_daham.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ad_course_ecom_daham.Business.Interfaces;

namespace ad_course_ecom_daham.Controllers
{
    public class AuthController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ISeriesService _seriesService;
        private readonly IComputerService _computerService;
        private readonly IVariationService _variationService;
        private readonly IVariationOptionService _variationOptionService;
        private readonly IOrderService _orderService;
        private readonly IOrderItemService _orderItemService;
        private readonly ICustomerService _customerService;
        List<Series> _seriesList;
        List<Category> _categories;
        List<Computer> _computerList;
        List<Order> _ordersList;
        List<Customer> _customersList;
        List<ComVariation> _variationList = new List<ComVariation>();
        public AuthController(IOrderItemService orderItemService, ICustomerService customerService, IOrderService orderService, IVariationOptionService variationOptionService, IVariationService variationService, ICategoryService categoryService, ISeriesService seriesService, IComputerService computerService)
        {
            _categoryService = categoryService;
            _seriesService = seriesService;
            _computerService = computerService;
            _variationService = variationService;
            _variationOptionService = variationOptionService;
            _orderService = orderService;
            _orderItemService = orderItemService;
            _customerService = customerService;
        }
        public IActionResult Index()
        {
            return View("../Auth/LoginView");
        }

        private bool HasEmailSign(string yourString)
        {
            return yourString.Contains("@");
        }

        [HttpPost]
        public IActionResult Login(string email, string password)
        {
            try {
                if(HasEmailSign(email))
                {
                    if (email == "admin@gmail.com")
                    {
                        _ordersList = _orderService.GetOrders();
                        _customersList = _customerService.GetCustomers();
                        for (int i = 0; i < _ordersList.Count; i++)
                        {
                            Customer customer = _customerService.GetCustomerById(_ordersList[i].cId);
                            _ordersList[i].customer = customer;
                            _ordersList[i].totalPrice = decimal.Round(_ordersList[i].totalPrice, 2, MidpointRounding.AwayFromZero);
                            List<OrderItem> orderItemList = _orderItemService.GetOrderItemById(_ordersList[i].oId);
                            _ordersList[i].orderItems = orderItemList;
                            for (int j = 0; j < _ordersList[i].orderItems.Count; j++)
                            {
                                Computer orderComputer = _computerService.GetComputerById(_ordersList[i].orderItems[j].comId);
                                _ordersList[i].orderItems[j].computer = orderComputer;
                            }
                        }
                        ViewBag.orders = _ordersList;
                        ViewBag.customers = _customersList;
                        ViewBag.isManageCategories = false;

                        List<DataPoint> dataPoints = new List<DataPoint>();
                        _computerList = _computerService.GetComputers();
                        for (int i = 0; i < _computerList.Count; i++)
                        {
                            dataPoints.Add(new DataPoint(_computerList[i].cName, _computerList[i].qty));
                        }

                        ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
                        ViewBag.errorLogin = "";
                        return View("../Admin/AdminDashboard");
                    }
                    else
                    {
                        Customer customer = _customerService.GetCustomerByName(email, password);
                        if (customer != null)
                        {
                            HttpContext.Session.SetString("cId", customer.cId.ToString());
                            List<Computer> computers = _computerService.GetComputers();
                            ViewBag.computers = computers;
                            return View("../Home/Index");
                        }
                        else
                        {
                            ViewBag.errorLogin = "Email or password you entered is incorrect.";
                            return View("../Auth/LoginView");
                        }
                    }
                }
                else
                {
                    ViewBag.errorLogin = "Email is not valid";
                    return View("../Auth/LoginView");
                }
            }
            catch(Exception e) {
                ViewBag.errorLogin = "Email or password you entered is incorrect. ";
                Console.WriteLine(e.ToString());
            }
            ViewBag.errorLogin = "Email or password you entered is incorrect. ";
            return View("../Auth/LoginView");
        }
    }
}

ad-course-ecom-daham/Controllers/OrderController.cs
using ad_course_ecom_daham.Business.Interfaces;
using ad_course_ecom_daham.Business.Services;
using Microsoft.AspNetCore.Mvc;

namespace ad_course_ecom_daham.Controllers
{
    public class OrderController : Controller
    {
        private readonly IComputerService _computerService;
        private readonly IVariationService _variationService;
        private readonly IVariationOptionService _variationOptionService;
        private readonly ICustomerService _customerService;

        public OrderController(IComputerService computerService, IVariationService variationService, 
            IVariationOptionService variationOptionService, ICustomerService customerService)
        {
            _computerService = computerService;
            _variationService = variationService;
            _variationOptionService = variationOptionService;
            _customerService = customerService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CheckoutAction(string comId, int qty)
        {
            return View();
        }
    }
}

ad-course-ecom-daham/Views/Product/EditProductView.cshtml
@model ad_course_ecom_daham.Models.Product.Computer;
@{
    ViewData["Title"] = "Edit Computers";
}
<div class="mt-1 w-25">
    <h4>Edit computer model: @ViewBag.computer.cName</h4>
    <form method="post" asp-controller="AdminDashboard" asp-action="UpdateComputer">
        <div class="form-group">
            <label for="exampleInputEmail1">Computer Name</label>
            <input type="text" class="form-control" name="cName" id="cName" asp-for="cName" value="@ViewBag.computer.cName" aria-describedby="emailHelp" placeholder="Enter computer name">

        </div>
        <div class="mb-1">
            <label>Select category type</label>
            <select name="cateName" value="@ViewBag.computer.cateName" class="form-control form-control-sm" asp-for="cateName">
                @foreach (var type in @ViewBag.categories)
                {
                    <option>@type.cateName</option>
                }
            </select>
        </div>
        <div class="mb-1">
            <label>Select series type</label>
            <select name="seriesName" value="@ViewBag.computer.seriesName" class="form-control form-control-sm" asp-for="seriesName">
                @foreach (var type in @ViewBag.series)
                {
                    <option>@type.seriesName</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Computer Genaral Price</label>
            <input type="number" class="form-control" name="normalPrice" id="normalPrice" value="@ViewBag.computer.normalPrice" asp-for="normalPrice" aria-describedby="emailHelp" placeholder="Enter computer price">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Computer Image URL</label>
            <input type="text" class="form-control" name="cImage" id="cImage" value="@ViewBag.computer.cImage" asp-for="cImage" aria-describedby="emailHelp" placeholder="Enter computer image URL">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Computer Quantity</label>
            <input type="number" class="form-control" name="qty" id="qty" asp-for="qty" value="@ViewBag.computer.qty" aria-describedby="emailHelp" placeholder="Enter qty">
        </div>
        <div class="dropdown-divider w-50 mb-1"></div>

        <button type="submit" class="btn btn-primary mt-2">Save Changes</button>
        <h6 class="text-success mb-4 mt-1">@ViewBag.computerStatus</h6>
    </form>

        <h2>@ViewBag.variation</h2>
        <div class="mb-1 mt-2">
            <h5>Edit Variation options</h5>
            @foreach (var item in @ViewBag.variationList)
            {
                <div class="text-sm-lef mb-1 mt-1">
                    Variation name: @item.comvName
                    <div class="m-2 ml-3" style="padding-left: 20px;">
                        <h6>Variation Options List</h6>
                        @foreach (var option in @item.variationOptions)
                        {
                            <div>
                                <div>
                                    @item.comvName option name: @option.comvopName
                                </div>
                                <div>
                                    @item.comvName price: @option.price
                                </div>
                                <div>
                                    @item.comvName available quantity: @option.quantity
                                </div>
                                <div class="dropdown-divider w-50 mb-1"></div>
                            </div>
                        }
                    <form method="post" asp-controller="AdminDashboard" asp-action="AddVariationOptions">
                        <input type="text" class="form-control" name="comvopName" id="comvopName" aria-describedby="emailHelp" placeholder="Enter Variation Option Name">
                        <input type="number" class="form-control" name="price" id="price" aria-describedby="emailHelp" placeholder="Enter Variation Option Price">
                        <input type="number" class="form-control" name="quantity" id="quantity" aria-describedby="emailHelp" placeholder="Enter Variation Option Qty">
                        <input type="text" style="display: none" class="form-control" name="comvId" value="@item.comvId" aria-describedby="emailHelp" placeholder="Enter computer name">
                        <button type="submit" class="btn btn-success mt-2 mb-2">Add a variation option</button>
                    </form>

                    </div>
                    <div class="dropdown-divider w-50 mb-1"></div>
                </div>
            }
        </div>
</div>

ad-course-ecom-daham/Views/Product/SingleProductView.cshtml
@{
    Layout = null;
}
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Customer Dashboard</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
    <!-- MDB -->
    <link rel="stylesheet" href="~/css/mdb.min.css" />
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/LineIcons.3.0.css" />
    <link rel="stylesheet" href="~/css/tiny-slider.css" />
    <link rel="stylesheet" href="~/css/glightbox.min.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw=="
            crossorigin="anonymous"></script>
</head>
<script type="text/javascript">

</script>
<!--Main Navigation-->
<header>
    <!-- Jumbotron -->
    <div class="p-3 text-center bg-white border-bottom">
        <div class="container">
            <div class="row gy-3">
                <!-- Left elements -->
                <div class="col-lg-2 col-sm-4 col-4">
                   <img src="https://cdn.pixabay.com/photo/2017/03/13/23/31/icon-2141485__340.png" height="45" />
                </div>
                <!-- Left elements -->
                <!-- Center elements -->
                <div class="order-lg-last col-lg-5 col-sm-8 col-8">
                    <div class="d-flex float-end">
                        <a class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center" asp-controller="Auth" asp-action="Index"> <i class="fas fa-user-alt m-1 me-md-2"></i><p class="d-none d-md-block mb-0">Sign out</p> </a>
                    </div>
                </div>
                <!-- Center elements -->
                <!-- Right elements -->
                <div class="col-lg-5 col-md-12 col-12">
                    <div class="input-group float-center">
                        <div class="form-outline">
                            <input type="search" id="form1" class="form-control" />
                            <label class="form-label" for="form1">Search</label>
                        </div>
                        <button type="button" class="btn btn-primary shadow-0">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
                <!-- Right elements -->
            </div>
        </div>
    </div>
    <!-- Jumbotron -->
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <!-- Container wrapper -->
        <div class="container justify-content-center justify-content-md-between">
            <!-- Toggle button -->
            <button class="navbar-toggler border py-2 text-dark"
                    type="button"
                    data-mdb-toggle="collapse"
                    data-mdb-target="#navbarLeftAlignExample"
                    aria-controls="navbarLeftAlignExample"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarLeftAlignExample">
                <!-- Left links -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-dark" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="#">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="#">Computer Serieses</a>
                    </li>
                </ul>
                <!-- Left links -->
            </div>
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
</header>
<!-- Start Item Details -->
<section class="item-details section">
    <div class="container">
        <div class="top-area">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-12 col-12">
                    <div class="product-images">
                        <main id="gallery">
                            <div class="main-img">
                                <img src="@ViewBag.computer.cImage" id="current" alt="#">
                            </div>
                        </main>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-12">
                    <div class="product-info">
                        <form method="post" asp-controller="Order" asp-action="CheckoutAction">
                            <h2 class="title">@ViewBag.computer.cName</h2>
                            <h3 name="price" class="price">Rs @decimal.Round(@ViewBag.computer.normalPrice, 2, MidpointRounding.AwayFromZero)</h3>
                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-12">
                                    <div class="form-group">
                                        @foreach (var variation in @ViewBag.variationList)
                                        {
                                            <label for="color">@variation.comvName</label>
                                            <select class="form-control" name="variation">
                                                @foreach (var option in @variation.variationOptions)
                                                {
                                                    <option>@option.comvopName</option>
                                                }
                                            </select>
                                        }
                                    </div>
                                </div>
                            </div>
                            <input type="number" class="form-control mt-2" max="@ViewBag.computer.qty" name="qty" id="qty" placeholder="Quantity">
                            <div class="bottom-content">
                                <div class="row align-items-end">
                                    <div class="col-lg-4 col-md-4 col-12">
                                        <div class="button cart-button">
                                            <button class="btn" style="width: 100%;">Check out</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Item Details -->